global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "airline_producer"
    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: "airline_consumer"
    static_configs:
      - targets: ["host.docker.internal:8002"]
